### ISSUE TITLE
Telemetry - Traceback (most recent call last) Errors

### ISSUE THREAD

**Issue by JimFran** [crewAIInc/crewAI#1023]
Hi team,

I'm trying to create a simple program (just to try the crewAI framework) to review some specific code file but I'm getting some errors and not sure if it's related to my code itself or I'm missing to import something.

This is my `main.py` file (I can provide the rest of the files if needed).

```shell
import warnings
from langchain._api import LangChainDeprecationWarning
warnings.simplefilter("ignore", category=LangChainDeprecationWarning)

from dotenv import load_dotenv
load_dotenv()

from crewai import Crew
from langchain.llms import OpenAI
from langchain_openai import ChatOpenAI

from tasks import Tasks
from agents import Agents

import os 

os.environ['OPENAI_MODEL_NAME'] = 'gpt-3.5-turbo-0125'
manager_llm=ChatOpenAI(model='gpt-3.5-turbo-0125'),

tasks = Tasks()
agents = Agents()

code_analyst_agent = agents.code_analyst_agent()
code_writer_agent = agents.code_writer_agent()
code_reviewer_agent = agents.code_reviewer_agent()

code_analyst_task = tasks.code_analyst_task(code_analyst_agent)
code_write_task = tasks.code_write_task(code_writer_agent)
code_review_task = tasks.code_review_task(code_reviewer_agent)

crew = Crew(
    agents=[code_analyst_agent, code_writer_agent, code_reviewer_agent],
    tasks=[
        code_analyst_task,
        code_write_task,
        code_review_task
    ]
)

# Kick off the process
result = crew.kickoff()

print("Code review completed")
print("Code improved:")
print(result)
```

and this is what I get as output:

```shell
py main.py

> Entering new CrewAgentExecutor chain...


> Entering new CrewAgentExecutor chain...


> Entering new CrewAgentExecutor chain...
Traceback (most recent call last):
  File "C:\Users\user\Desktop\crewai\main.py", line 45, in <module>
    result = crew.kickoff()
             ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\crew.py", line 468, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\crew.py", line 603, in _run_sequential_process
    return self._execute_tasks(self.tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\crew.py", line 692, in _execute_tasks
    task_output = task.execute_sync(
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\task.py", line 175, in execute_sync
    return self._execute_core(agent, context, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\task.py", line 228, in _execute_core
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agent.py", line 206, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agent.py", line 206, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agent.py", line 205, in execute_task
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agent.py", line 195, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 166, in invoke
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agents\executor.py", line 70, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 1318, in _take_next_step
    [
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 1318, in <listcomp>
    [
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\crewai\agents\executor.py", line 134, in _iter_next_step
    output = self.agent.plan(  # type: ignore #  Incompatible types in assignment (expression has type "AgentAction | AgentFinish | list[AgentAction]", variable has type "AgentAction")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 463, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 3253, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 3240, in transform
    yield from self._transform_stream_with_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 2053, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 3202, in _transform
    for output in final_pipeline:
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 1271, in transform
    for ichunk in input:
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 5267, in transform
    yield from self.bound.transform(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\runnables\base.py", line 1289, in transform
    yield from self.stream(final, config, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 373, in stream
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 353, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_openai\chat_models\base.py", line 521, in _stream
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\chat\completions.py", line 646, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1031, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1031, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
```

Any ideas?

**Comment by TusharP05** [comment]
similar issue, also getting telemetry timed out issue!

**Comment by theCyberTech** [comment]
We had a small issue with our Telemetry service yesterday which we resolved, please let us know it it is still happening

**Comment by JimFran** [comment]
@theCyberTech I'm still getting the same output. Do you think it may be related to my code?

**Comment by Simone-meli25** [comment]
I'm also facing right now an exception relative to telemetry

**Comment by Simone-meli25** [comment]
> We had a small issue with our Telemetry service yesterday which we resolved, please let us know it it is still happening

i still face the error

**Comment by JimFran** [comment]
I tried to run again the script this week and still facing the same error. Please, could someone give some advice on this? cc @theCyberTech
