### ISSUE TITLE
Importing the libraries for CrewAI fails

### ISSUE THREAD

**Issue by dyioulos** [crewAIInc/crewAI#1045]
System OS: RHEL 9.4
Python version: 3.9.18

```
>>> from crewai import Agent, Task, Crew, Process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/crewai/__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "/usr/local/lib/python3.9/site-packages/crewai/agent.py", line 22, in <module>
    from crewai.agents import (
  File "/usr/local/lib/python3.9/site-packages/crewai/agents/__init__.py", line 2, in <module>
    from .executor import CrewAgentExecutor
  File "/usr/local/lib/python3.9/site-packages/crewai/agents/executor.py", line 16, in <module>
    from crewai.utilities import I18N
  File "/usr/local/lib/python3.9/site-packages/crewai/utilities/__init__.py", line 4, in <module>
    from .rpm_controller import RPMController
  File "/usr/local/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 10, in <module>
    class RPMController(BaseModel):
  File "/usr/local/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 15, in RPMController
    _timer: threading.Timer | None = PrivateAttr(default=None)
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by gadgethome** [comment]
Hi the minimum requirement for python is 3.10 please see https://docs.crewai.com/getting-started/Installing-CrewAI/

**Comment by dyioulos** [comment]
Thank you. Does ver. 0.5.0 also include  crewai-tools?

**Comment by gadgethome** [comment]
If you run
**pip install -U crewai[tools]** and these are the latest versions as of now
crewai                                   0.41.1
crewai-tools                          0.4.26

Then use something like poetry to set up your environment. thanks

**Comment by theCyberTech** [comment]
Hi @dyioulos ,

As mentioned above please ensure your Python version is within the correct supported range please see docs:

https://docs.crewai.com/getting-started/Installing-CrewAI/
