### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'google.cloud.location'

### ISSUE THREAD

**Issue by mszenigAsignate** [crewAIInc/crewAI#1267]
### Description

Since I've upgraded crewai to the latest version:
No matter which crewai script i want to run, i always get the same error
i've tried downgrading the version, etc... nothing works for me...

this is the complete outupt in the terminal:

```
/Users/user111/Library/Python/3.11/lib/python/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/Users/user111/Documents/AIAgent-Sales/main.py", line 2, in <module>
    from crewai import Agent, Task, Crew, Process
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/agent.py", line 13, in <module>
    from crewai.agents import CacheHandler, CrewAgentExecutor, CrewAgentParser
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/agents/__init__.py", line 2, in <module>
    from .executor import CrewAgentExecutor
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/agents/executor.py", line 19, in <module>
    from crewai.agents.agent_builder.base_agent_executor_mixin import CrewAgentExecutorMixin
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/agents/agent_builder/base_agent_executor_mixin.py", line 4, in <module>
    from crewai.memory.entity.entity_memory_item import EntityMemoryItem
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/memory/__init__.py", line 1, in <module>
    from .entity.entity_memory import EntityMemory
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/memory/entity/entity_memory.py", line 3, in <module>
    from crewai.memory.storage.rag_storage import RAGStorage
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/memory/storage/rag_storage.py", line 9, in <module>
    from crewai.utilities.paths import db_storage_path
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/utilities/__init__.py", line 4, in <module>
    from .instructor import Instructor
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/crewai/utilities/instructor.py", line 3, in <module>
    import instructor
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/instructor/__init__.py", line 79, in <module>
    from .client_vertexai import from_vertexai
  File "/Users/user111/Library/Python/3.11/lib/python/site-packages/instructor/client_vertexai.py", line 5, in <module>
    from vertexai.preview.generative_models import ToolConfig  # type: ignore[reportMissingTypeStubs]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vertexai/__init__.py", line 17, in <module>
    from google.cloud.aiplatform import version as aiplatform_version
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
    from google.cloud.aiplatform import initializer
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform/initializer.py", line 33, in <module>
    from google.cloud.aiplatform import compat
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform/compat/__init__.py", line 18, in <module>
    from google.cloud.aiplatform.compat import services
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform/compat/services/__init__.py", line 18, in <module>
    from google.cloud.aiplatform_v1beta1.services.dataset_service import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform_v1beta1/__init__.py", line 21, in <module>
    from .services.dataset_service import DatasetServiceClient
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/__init__.py", line 16, in <module>
    from .client import DatasetServiceClient
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/client.py", line 64, in <module>
    from google.cloud.location import locations_pb2  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'google.cloud.location'
```
### Steps to Reproduce

1. Go to Visual Studio Code
2. run any crewai script

or run it from terminal

### Expected behavior

i used to get results from crewai

### Screenshots/Code snippets

.

### Operating System

macOS Sonoma

### Python Version

3.11

### crewAI Version

0.51.0

### crewAI Tools Version

.

### Virtual Environment

Venv

### Evidence

.

### Possible Solution

.

### Additional context

.

**Comment by mszenigAsignate** [comment]
i solved it by installing vertexai (pip install vertexai)
