### ISSUE TITLE
[BUG] How to use crewAI 0.76.9 with AWS bedrock 

### ISSUE THREAD

**Issue by gyliu513** [crewAIInc/crewAI#1561]
### Description

There is a similar issue but it got closed https://github.com/crewAIInc/crewAI/issues/403 , but still have some issue.

Here is the code

```python
from dotenv import load_dotenv
load_dotenv()

from crewai import Agent, Task, Crew, Process, LLM
from crewai_tools import SerperDevTool

search_tool = SerperDevTool()

llm = LLM(
    model="bedrock/anthropic.claude-v2",
    region_name="us-east-1",
)

# Define your agents with roles and goals
researcher = Agent(
  role='Senior Research Analyst',
  goal='Uncover cutting-edge developments in AI and data science',
  backstory="""You work at a leading tech think tank.
  Your expertise lies in identifying emerging trends.
  You have a knack for dissecting complex data and presenting actionable insights.""",
  verbose=True,
  llm=llm,
  allow_delegation=False,
  tools=[search_tool]
)
writer = Agent(
  role='Tech Content Strategist',
  goal='Craft compelling content on tech advancements',
  backstory="""You are a renowned Content Strategist, known for your insightful and engaging articles.
  You transform complex concepts into compelling narratives.""",
  verbose=True,
  llm=llm,
  allow_delegation=True
)

# Create tasks for your agents
task1 = Task(
  description="""Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.""",
  expected_output="Full analysis report in bullet points",
  agent=researcher
)

task2 = Task(
  description="""Using the insights provided, develop an engaging blog
  post that highlights the most significant AI advancements.
  Your post should be informative yet accessible, catering to a tech-savvy audience.
  Make it sound cool, avoid complex words so it doesn't sound like AI.""",
  expected_output="Full blog post of at least 4 paragraphs",
  agent=writer
)

# Instantiate your crew with a sequential process
crew = Crew(
  agents=[researcher],
  tasks=[task1],
  verbose=True,
  process = Process.sequential
)

def crew_kickoff():
    # Get your crew to work!
    return crew.kickoff()

print("######################")
result = crew_kickoff()
print(result)
```

### Steps to Reproduce

It reports I do not have permission to access the model, I used the following models, but both does not work

- model="bedrock/anthropic.claude-v2",
- model="anthropic.claude-v2",

```console
(bedrock1) gyliu@guangyas-air ~ % /Users/gyliu/bedrock1/bin/python /Users/gyliu/go/src/github.com/gyliu513/langX101/crew/crewai-be
drock-2.py
######################
# Agent: Senior Research Analyst
## Task: Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.
2024-11-05 22:05:09,102 - 8716095296 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}
# Agent: Senior Research Analyst
## Task: Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.
2024-11-05 22:05:09,301 - 8716095296 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}
# Agent: Senior Research Analyst
## Task: Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.
2024-11-05 22:05:09,503 - 8716095296 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}
Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 413, in completion
    response = client.post(url=proxy_endpoint_url, headers=prepped.headers, data=data)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 386, in post
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 372, in post
    response.raise_for_status()
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-v2/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2563, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 417, in completion
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.common_utils.BedrockError: {"message":"You don't have access to the model with the specified model ID."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 1013, in wrapper
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2998, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2085, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 413, in completion
    response = client.post(url=proxy_endpoint_url, headers=prepped.headers, data=data)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 386, in post
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 372, in post
    response.raise_for_status()
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-v2/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2563, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 417, in completion
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.common_utils.BedrockError: {"message":"You don't have access to the model with the specified model ID."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 1013, in wrapper
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2998, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2085, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 413, in completion
    response = client.post(url=proxy_endpoint_url, headers=prepped.headers, data=data)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 386, in post
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 372, in post
    response.raise_for_status()
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-v2/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2563, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 417, in completion
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.common_utils.BedrockError: {"message":"You don't have access to the model with the specified model ID."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gyliu/go/src/github.com/gyliu513/langX101/crew/crewai-bedrock-2.py", line 67, in <module>
    result = crew_kickoff()
             ^^^^^^^^^^^^^^
  File "/Users/gyliu/go/src/github.com/gyliu513/langX101/crew/crewai-bedrock-2.py", line 64, in crew_kickoff
    return crew.kickoff()
           ^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/crew.py", line 494, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/crew.py", line 598, in _run_sequential_process
    return self._execute_tasks(self.tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/crew.py", line 696, in _execute_tasks
    task_output = task.execute_sync(
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/task.py", line 191, in execute_sync
    return self._execute_core(agent, context, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/task.py", line 247, in _execute_core
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 248, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 248, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 247, in execute_task
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 1013, in wrapper
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/main.py", line 2998, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/Users/gyliu/bedrock1/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2085, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: BedrockException - {"message":"You don't have access to the model with the specified model ID."}
```

### Expected behavior

How can I get the supported model list for CrewAI? CrewAI 0.76.9 is using LiteLLM, this seems to be a question for LiteLLM?

### Screenshots/Code snippets

as above

### Operating System

macOS Sonoma

### Python Version

3.11

### crewAI Version

0.76.9

### crewAI Tools Version

0.13.4

### Virtual Environment

Venv

### Evidence

as above

### Possible Solution

None

### Additional context

No

**Comment by gyliu513** [comment]
Seems I need to set three env in .env, this works.

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION_NAME
```

**Comment by Abhinagra** [comment]
Hi @gyliu513 i have set the variables in my .env file and then using load_dotenv to load them as well, but i am still getting the same error that i don't have access to the models. My code syntax is similar as yours could you please tell me what possibly i am doing wrong?

**Comment by Abhinagra** [comment]
This is my code:
@gyliu513 

import os
import yaml
from crewai import Agent, Task, Crew, LLM
from typing import List
from pydantic import BaseModel, Field
from IPython.display import display, Markdown
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")
aws_default_region= os.getenv("AWS_DEFAULT_REGION")

llm = LLM(
    model="bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
    region_name="us-east-1",
)
# Define file paths for YAML configurations
files = {
    'agents': "C:\\Users\\adatta\\Downloads\\bedrocktest\\agents.yaml",
    'tasks': "C:\\Users\\adatta\\Downloads\\bedrocktest\\tasks.yaml"
}

# Load configurations from YAML files
configs = {}
for config_type, file_path in files.items():
    with open(file_path, 'r') as file:
        configs[config_type] = yaml.safe_load(file)

# Assign loaded configurations to specific variables
agents_config = configs['agents']
tasks_config = configs['tasks']


class TaskEstimate(BaseModel):
    task_name: str = Field(..., description="Name of the task")
    estimated_time_hours: float = Field(..., description="Estimated time to complete the task in hours")
    required_resources: List[str] = Field(..., description="List of resources required to complete the task")

class Milestone(BaseModel):
    milestone_name: str = Field(..., description="Name of the milestone")
    tasks: List[str] = Field(..., description="List of task IDs associated with this milestone")

class ProjectPlan(BaseModel):
    tasks: List[TaskEstimate] = Field(..., description="List of tasks with their estimates")
    milestones: List[Milestone] = Field(..., description="List of project milestones")


# Creating Agents
project_planning_agent = Agent(
  config=agents_config['project_planning_agent'],
  llm=llm
)

estimation_agent = Agent(
  config=agents_config['estimation_agent'],
  llm=llm
)

resource_allocation_agent = Agent(
  config=agents_config['resource_allocation_agent'],
  llm=llm
)

# Creating Tasks
task_breakdown = Task(
  config=tasks_config['task_breakdown'],
  agent=project_planning_agent
)

time_resource_estimation = Task(
  config=tasks_config['time_resource_estimation'],
  agent=estimation_agent
)

resource_allocation = Task(
  config=tasks_config['resource_allocation'],
  agent=resource_allocation_agent,
  output_pydantic=ProjectPlan # This is the structured output we want
)

# Creating Crew
crew = Crew(
  agents=[
    project_planning_agent,
    estimation_agent,
    resource_allocation_agent
  ],
  tasks=[
    task_breakdown,
    time_resource_estimation,
    resource_allocation
  ],
  embedder={
            "provider": "huggingface",
            "config": {"model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"},
        },
  verbose=True
)

project = 'Website'
industry = 'Technology'
project_objectives = 'Create a website for a small business'
team_members = """
- John Doe (Project Manager)
- Jane Doe (Software Engineer)
- Bob Smith (Designer)
- Alice Johnson (QA Engineer)
- Tom Brown (QA Engineer)
"""
project_requirements = """
- Create a responsive design that works well on desktop and mobile devices
- Implement a modern, visually appealing user interface with a clean look
- Develop a user-friendly navigation system with intuitive menu structure
- Include an "About Us" page highlighting the company's history and values
- Design a "Services" page showcasing the business's offerings with descriptions
- Create a "Contact Us" page with a form and integrated map for communication
- Implement a blog section for sharing industry news and company updates
- Ensure fast loading times and optimize for search engines (SEO)
- Integrate social media links and sharing capabilities
- Include a testimonials section to showcase customer feedback and build trust
"""

# Format the dictionary as Markdown for a better display in Jupyter Lab
formatted_output = f"""
**Project Type:** {project}

**Project Objectives:** {project_objectives}

**Industry:** {industry}

**Team Members:**
{team_members}
**Project Requirements:**
{project_requirements}
"""
# Display the formatted output as Markdown
display(Markdown(formatted_output))

# The given Python dictionary
inputs = {
  'project_type': project,
  'project_objectives': project_objectives,
  'industry': industry,
  'team_members': team_members,
  'project_requirements': project_requirements
}

result = crew.kickoff(

  inputs=inputs
)

**Comment by gyliu513** [comment]
```
llm = LLM(
model="bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
region_name="us-east-1",
)
```

@Abhinagra please make sure you have permission to access `bedrock/anthropic.claude-3-sonnet-20240229-v1:0"` in `us-east-1`, you can test this via bedrock UI. I think you may not able to access `bedrock/anthropic.claude-3-sonnet-20240229-v1:0"` in `us-east-1`, please have a try and good luck.
