### ISSUE TITLE
[BUG] Ollama and default project

### ISSUE THREAD

**Issue by 360d-io-labs** [crewAIInc/crewAI#1584]
### Description

When using the command crewai create crew projectname with crewai 0.79.4 it will configure the .env with the information but when you will run the project you will get a missing key_name error

### Steps to Reproduce

1. install crewai 0.79.4
2. crewai create crew projectname
3. select ollama and ollama/llama3.1
4. crewai run

### Expected behavior

Should run the demo project

### Screenshots/Code snippets

The .env file contains:

MODEL=ollama/llama3.1
API_BASE=http://localhost:11434/

### Operating System

Ubuntu 24.04

### Python Version

3.12

### crewAI Version

0.79.4

### crewAI Tools Version

0.14.0

### Virtual Environment

Venv

### Evidence

Traceback (most recent call last):
  File "/root/crewai/latest_ai_development/.venv/bin/run_crew", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/crewai/latest_ai_development/src/latest_ai_development/main.py", line 21, in run
    LatestAiDevelopment().crew().kickoff(inputs=inputs)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/crewai/project/crew_base.py", line 35, in __init__
    self.map_all_task_variables()
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/crewai/project/crew_base.py", line 145, in map_all_task_variables
    self._map_task_variables(
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/crewai/project/crew_base.py", line 178, in _map_task_variables
    self.tasks_config[task_name]["agent"] = agents[agent_name]()
                                            ^^^^^^^^^^^^^^^^^^^^
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/crewai/project/utils.py", line 7, in memoized_func
    cache[key] = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/root/crewai/latest_ai_development/src/latest_ai_development/crew.py", line 30, in researcher
    return Agent(
           ^^^^^^
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/crewai/latest_ai_development/.venv/lib/python3.12/site-packages/crewai/agent.py", line 160, in post_init_setup
    if env_var["key_name"] in unnacepted_attributes:
       ~~~~~~~^^^^^^^^^^^^
KeyError: 'key_name'
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.
has context menu

### Possible Solution

None

### Additional context

Trying to run the simple demo project with a local ollama installation

**Comment by auphof** [comment]
I have the same issue trying to use `ollama` provider with `crewai version: 0.79.4`

I have a workaround, and i believe a fix that I will submit as a PR

# 🚧 The workaround 

```python
# WORKAROUND for issue: https://github.com/crewai/crewai/issues/1584
# Place this in the main.py before the crew import
from crewai.cli.constants import ENV_VARS
ENV_VARS.update(
    {"ollama":
      [{
            "prompt": "Enter your OLLAMA API_BASE (press Enter to skip)",
            "key_name": "API_BASE",
        },
        # {
        #     "default": True,
        #     "API_BASE": "http://localhost:11434",
        # }
    ]})
```

#  🔍CHECK
ensure API_BASE is correctly configured in the `.env` file ie: `API_BASE=http://localhost:11434`

your `main.py` should then look something like 
![image](https://github.com/user-attachments/assets/44bdaf14-d680-4026-a189-e7c033ab7422)
