### ISSUE TITLE
[BUG] KeyError: 'key_name' during crewAI execution

### ISSUE THREAD

**Issue by Jacques-Murray** [crewAIInc/crewAI#1682]
### Description

When running the crewAI project, a KeyError: 'key_name' occurs during the initialization of the Agent in the researcher method. This prevents the crew task from kicking off properly.

### Steps to Reproduce

1. Run the crew with `crewai run`.
2. Observe the traceback and error message.

### Expected behavior

The crew task should initialize all agents and tasks successfully and kick off without errors.

### Screenshots/Code snippets

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Scripts\run_crew.exe\__main__.py", line 8, in <module>
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\src\personalized_content_creator\main.py", line 21, in run
    PersonalizedContentCreator().crew().kickoff(inputs=inputs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\crewai\project\crew_base.py", line 35, in __init__
    self.map_all_task_variables()
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\crewai\project\crew_base.py", line 166, in map_all_task_variables
    self._map_task_variables(
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\crewai\project\crew_base.py", line 199, in _map_task_variables
    self.tasks_config[task_name]["agent"] = agents[agent_name]()
                                            ^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\crewai\project\utils.py", line 7, in memoized_func
    cache[key] = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\src\personalized_content_creator\crew.py", line 42, in researcher
    return Agent(
           ^^^^^^
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\PersonalizedContentCreator\personalized_content_creator\.venv\Lib\site-packages\crewai\agent.py", line 165, in post_init_setup
    env_value = os.environ.get(env_var["key_name"])
                               ~~~~~~~^^^^^^^^^^^^
KeyError: 'key_name'
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.

### Operating System

Windows 11

### Python Version

3.11

### crewAI Version

0.83.0

### crewAI Tools Version

1.0.0

### Virtual Environment

Conda

### Evidence

The KeyError occurs in the env_value = os.environ.get(env_var["key_name"]) line of crewAI during post-init setup for the Agent. This suggests the env_var dictionary may not contain the key key_name as expected.

### Possible Solution

for provider, env_vars in ENV_VARS.items():
        if provider == set_provider:
            for env_var in env_vars:
                if isinstance(env_var, str):
                    # If env_var is a string, assume it's the environment variable name
                    env_value = os.environ.get(env_var)
                    if env_value:
                        param_name = env_var.lower()
                        if "api_key" in param_name:
                            param_name = "api_key"
                        elif "api_base" in param_name:
                            param_name = "api_base"
                        elif "api_version" in param_name:
                            param_name = "api_version"
                        llm_params[param_name] = env_value
                elif isinstance(env_var, dict):
                    # If env_var is a dict, look for 'key_name' or other known keys
                    key_name = env_var.get("key_name") or next((k for k in env_var if k != "default"), None)
                    if key_name and key_name not in unaccepted_attributes:
                        env_value = os.environ.get(key_name)
                        if env_value:
                            param_name = key_name.lower()
                            if "api_key" in param_name:
                                param_name = "api_key"
                            elif "api_base" in param_name:
                                param_name = "api_base"
                            elif "api_version" in param_name:
                                param_name = "api_version"
                            llm_params[param_name] = env_value
                    elif env_var.get("default", False):
                        for key, value in env_var.items():
                            if key not in ["prompt", "key_name", "default"]:
                                if key in os.environ:
                                    llm_params[key] = value
                else:
                    print(f"Warning: Unexpected env_var format: {env_var}")

    self.llm = LLM(**llm_params)

### Additional context

The issue might be related to a missing or misconfigured environment variable required for the Agent setup. Ensure all dependencies are installed and properly configured.

**Comment by Jacques-Murray** [comment]
I'm busy implementing a fix on my fork.
