### ISSUE TITLE
SOLVED: Error installing on Ubuntu 22.04, missing C++ at least v11

### ISSUE THREAD

**Issue by lordpba** [crewAIInc/crewAI#501]
SOLVED: pip install crewai has an error due to missing C++ version 11 compiler:
----------------------------------------------------------------------------------------------------------
Building wheels for collected packages: chroma-hnswlib
  Building wheel for chroma-hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for chroma-hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating tmp
      gcc -pthread -B /home/mario/anaconda3/envs/AI_Magi_env/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/mario/anaconda3/envs/AI_Magi_env/include -fPIC -O2 -isystem /home/mario/anaconda3/envs/AI_Magi_env/include -fPIC -I/home/mario/anaconda3/envs/AI_Magi_env/include/python3.12 -c /tmp/tmpjh4dkkgb.cpp -o tmp/tmpjh4dkkgb.o -std=c++14
      gcc -pthread -B /home/mario/anaconda3/envs/AI_Magi_env/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/mario/anaconda3/envs/AI_Magi_env/include -fPIC -O2 -isystem /home/mario/anaconda3/envs/AI_Magi_env/include -fPIC -I/home/mario/anaconda3/envs/AI_Magi_env/include/python3.12 -c /tmp/tmp7u1hon26.cpp -o tmp/tmp7u1hon26.o -std=c++11
      Traceback (most recent call last):
        File "/home/mario/anaconda3/envs/AI_Magi_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mario/anaconda3/envs/AI_Magi_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mario/anaconda3/envs/AI_Magi_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 115, in <module>
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-mlap9xe2/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 102, in build_extensions
        File "<string>", line 69, in cpp_flag
      RuntimeError: Unsupported compiler -- at least C++11 support is needed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib
Failed to build chroma-hnswlib
ERROR: Could not build wheels for chroma-hnswlib, which is required to install pyproject.toml-based projects

----------------------------------------------------------------------------------------------------------

solution is:
sudo apt install build-essential

----------------------------------------------------------------------------------------------------------

Hope can be useful to others :)))

**Comment by Cap0n3** [comment]
(Just in case) To resolve this issue on Fedora version 32 or newer, you'll need to install execute the following command in the terminal to install the necessary development tools and libraries (equivalent of the `build-essential` package) :

```console
sudo dnf groupinstall "Development Tools" "Development Libraries"
```

**Comment by GeorgeMyller** [comment]
can I fix it on a Macbook?

**Comment by GeorgeMyller** [comment]
> don't know, but you can try as Macbook is Unix based:
> 
> sudo apt install build-essential
> 
> let us know!

The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

**Comment by GeorgeMyller** [comment]
I installed Java again but don't work.
