### ISSUE TITLE
The getting started code is failing while running

### ISSUE THREAD

**Issue by vizsatiz** [crewAIInc/crewAI#565]
New to crewai, tried the getting started doc, and got stuck with this error:
Link: https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/#introduction

Python Version: 3.11.6

```
/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
Traceback (most recent call last):
  File "/Users/vizsatiz/Documents/hub/root-agents/agent.py", line 71, in <module>
    crew = Crew(
           ^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/crewai/crew.py", line 166, in create_crew_memory
    self._short_term_memory = ShortTermMemory(embedder_config=self.embedder)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/crewai/memory/short_term/short_term_memory.py", line 16, in __init__
    storage = RAGStorage(type="short_term", embedder_config=embedder_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/crewai/memory/storage/rag_storage.py", line 70, in __init__
    self.app = App.from_config(config=config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/embedchain/app.py", line 397, in from_config
    return cls(
           ^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/embedchain/app.py", line 117, in __init__
    self._init_db()
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/embedchain/app.py", line 140, in _init_db
    self.db._initialize()
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 75, in _initialize
    self._get_or_create_collection(self.config.collection_name)
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 107, in _get_or_create_collection
    self.collection = self.client.get_or_create_collection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/api/client.py", line 237, in get_or_create_collection
    return self._server.get_or_create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 217, in get_or_create_collection
    return self.create_collection(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 167, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 209, in create_collection
    existing = self.get_collections(name=name, tenant=tenant, database=database)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vizsatiz/Documents/hub/root-agents/.venv/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 435, in get_collections
    rows = cur.execute(sql, params).fetchall()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: collections.topic
```

**Comment by alexfazio** [comment]
It appears that you are querying a database? Which is not the scope of `https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/#introduction`

I recommend referring to these templates, particularly the one for the PostgreSQL tool. ↓

After reviewing them, please let me know if you are able to identify any pointers to fix your problem:

https://github.com/alexfazio/crewAI-quickstart
