### ISSUE TITLE
Crewai  Library  Running Fails

### ISSUE THREAD

**Issue by itxabdullahbinasad** [crewAIInc/crewAI#649]
I think there is an issue with the library getting this error 

> Entering new CrewAgentExecutor chain...
Exception in thread Thread-1 (_execute):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner        
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\crewai\task.py", line 192, in _execute
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\crewai\agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\crewai\agents\executor.py", line 128, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain\agents\agent.py", line 1138, in _take_next_step
    [
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain\agents\agent.py", line 1138, in <listcomp>
    [
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\crewai\agents\executor.py", line 192, in _iter_next_step
    output = self.agent.plan(  # type: ignore #  Incompatible types in assignment (expression has type "AgentAction | AgentFinish | list[AgentAction]", variable has type "AgentAction")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain\agents\agent.py", line 397, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2875, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2862, in transform
    yield from self._transform_stream_with_config(
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1881, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2826, in _transform
    for output in final_pipeline:
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1282, in transform
    for ichunk in input:
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 4736, in transform
    yield from self.bound.transform(
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1282, in transform
    for ichunk in input:
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1282, in transform
    for ichunk in input:
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 3246, in transform
    yield from self._transform_stream_with_config(
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1881, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 3219, in _transform
    futures = {
              ^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 3220, in <dictcomp>
    executor.submit(next, generator): (step_name, generator)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABAX\Desktop\AutoLinkedinPoster\.venv\Lib\site-packages\langchain_core\runnables\config.py", line 452, in submit
    return super().submit(
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 169, in submit   
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
PS C:\Users\ABAX\Desktop\AutoLinkedinPoster>

**Comment by nigel-daniels** [comment]
I'm also seeing the same error.
