### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by lvchongen** [crewAIInc/crewAI#695]
After executed the crew.kickoff(), it would throw below error:

role = cast(str, _dict.get("role"))
                     ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by lugq1990** [comment]
is that possible to provide the full stack log info to get some insight?

**Comment by lvchongen** [comment]
Traceback (most recent call last):
  File "/Users/chongenlv/PycharmProjects/AICoder/main.py", line 72, in <module>
    result = automation_crew.run()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/PycharmProjects/AICoder/main.py", line 61, in run
    result = crew.kickoff()
             ^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/crew.py", line 264, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/crew.py", line 305, in _run_sequential_process
    output = task.execute(context=task_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/task.py", line 183, in execute
    result = self._execute(
             ^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/task.py", line 192, in _execute
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/agents/executor.py", line 128, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain/agents/agent.py", line 1138, in _take_next_step
    [
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/crewai/agents/executor.py", line 192, in _iter_next_step
    output = self.agent.plan(  # type: ignore #  Incompatible types in assignment (expression has type "AgentAction | AgentFinish | list[AgentAction]", variable has type "AgentAction")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain/agents/agent.py", line 397, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2875, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2862, in transform
    yield from self._transform_stream_with_config(
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1881, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2826, in _transform
    for output in final_pipeline:
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1282, in transform
    for ichunk in input:
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 4736, in transform
    yield from self.bound.transform(
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1300, in transform
    yield from self.stream(final, config, **kwargs)
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 249, in stream
    raise e
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 229, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 416, in _stream
    chunk = _convert_delta_to_message_chunk(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chongenlv/Documents/conda/anaconda3/envs/Automation/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 161, in _convert_delta_to_message_chunk
    role = cast(str, _dict.get("role"))
                     ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
