### ISSUE TITLE
Error (i think a timeout error) using ChatGPT-4o via Azure. 

### ISSUE THREAD

**Issue by robertobalestri** [crewAIInc/crewAI#703]
Library httpx goes in timeout if the model takes too long. Is there a way to change timeout time to let it wait a little longer?

Traceback (most recent call last):
  File "d:\DATA\dev\CREWAI NARRATIVE EXTRACTION\main.py", line 8, in <module>
    result = main_crew.kickoff()
             ^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\crew.py", line 264, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\crew.py", line 305, in _run_sequential_process
    output = task.execute(context=task_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\task.py", line 183, in execute
    result = self._execute(
             ^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\task.py", line 192, in _execute
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\agent.py", line 236, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\agents\executor.py", line 128, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain\agents\agent.py", line 1138, in _take_next_step
    [
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain\agents\agent.py", line 1138, in <listcomp>
    [
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\crewai\agents\executor.py", line 192, in _iter_next_step
    output = self.agent.plan(  # type: ignore #  Incompatible types in assignment (expression has type "AgentAction | AgentFinish | list[AgentAction]", variable has type "AgentAction")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain\agents\agent.py", line 397, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2875, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2862, in transform
    yield from self._transform_stream_with_config(
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1881, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 2826, in _transform
    for output in final_pipeline:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1282, in transform
    for ichunk in input:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 4736, in transform
    yield from self.bound.transform(
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 1300, in transform
    yield from self.stream(final, config, **kwargs)
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 249, in stream  
    raise e
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 229, in stream  
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\langchain_openai\chat_models\base.py", line 408, in _stream
    for chunk in self.client.create(messages=message_dicts, **params):
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\agentops\llm_tracker.py", line 186, in generator
    for chunk in response:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\openai\_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\openai\_streaming.py", line 58, in __stream__
    for sse in iterator:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\openai\_streaming.py", line 50, in _iter_events
    yield from self._decoder.iter_bytes(self.response.iter_bytes())
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\openai\_streaming.py", line 280, in iter_bytes
    for chunk in self._iter_chunks(iterator):
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\openai\_streaming.py", line 291, in _iter_chunks
    for chunk in iterator:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\httpx\_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\httpx\_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\httpx\_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\httpx\_transports\default.py", line 112, in __iter__
    with map_httpcore_exceptions():
  File "c:\Users\rbale\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\DATA\dev\CREWAI NARRATIVE EXTRACTION\.venv\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions   
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by hthouse** [comment]
I am also getting same error , does anyone have suggestions ?

**Comment by imnotdev25** [comment]
Are you using Langchain Client ?

**Comment by hthouse** [comment]
Yes, 
from langchain_openai import AzureChatOpenAI
