### ISSUE TITLE
ubuntu22 crewai v0.35.3: importlib.metadata.PackageNotFoundError: No package metadata was found for embedchain

### ISSUE THREAD

**Issue by neo896** [crewAIInc/crewAI#842]
os: linux(ubuntu22)
python: 3.10.14
crewai version: v0.35.3
Error: importlib.metadata.PackageNotFoundError: No package metadata was found for embedchain

**Comment by joaomdmoura** [comment]
Yup! I just got that error as well, I think it's fixed now, do you mind trying 0.35.4?

**Comment by robsonc** [comment]
I receive the same error on windows.. crewai 0.35.4

steps to reproduce

pip install crewai -- upgrade
crewai add project_name
cd project_name
poetry lock
poetry install
poetry run project_name


Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\PythonProjects\ebook_saas\src\ebook_saas\main.py", line 3, in <module>
    from ebook_saas.crew import EbookSaasCrew
  File "E:\PythonProjects\ebook_saas\src\ebook_saas\crew.py", line 1, in <module>
    from crewai import Agent, Crew, Process, Task
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\agent.py", line 13, in <module>
    from crewai.agents import CacheHandler, CrewAgentExecutor, CrewAgentParser
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\agents\__init__.py", line 2, in <module>
    from .executor import CrewAgentExecutor
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\agents\executor.py", line 14, in <module>
    from crewai.agents.agent_builder.base_agent_executor_mixin import CrewAgentExecutorMixin
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\agents\agent_builder\base_agent_executor_mixin.py", line 3, in <module>
    from crewai.memory.entity.entity_memory_item import EntityMemoryItem
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\memory\__init__.py", line 1, in <module>
    from .entity.entity_memory import EntityMemory
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\memory\entity\entity_memory.py", line 3, in <module>
    from crewai.memory.storage.rag_storage import RAGStorage
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\crewai\memory\storage\rag_storage.py", line 7, in <module>
    from embedchain import App
  File "E:\PythonProjects\ebook_saas\.venv\Lib\site-packages\embedchain\__init__.py", line 3, in <module>
    __version__ = importlib.metadata.version(__package__ or __name__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 889, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for embedchain

**Comment by neo896** [comment]
After upgrading to v0.35.7, it fixed the problem
