### ISSUE TITLE
Your system has an unsupported version of sqlite3.

### ISSUE THREAD

**Issue by KGKallasmaa** [crewAIInc/crewAI#989]
Hey, I was trying to create a simple crew ai + fastapi application, and I ran into this issue.

` RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
`

Versions:
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uvicorn = "^0.30.3"
crewai = "^0.41.1"
fastapi = "^0.111.1"

**Comment by theCyberTech** [comment]
Hi @KGKallasmaa 
What OS are you using?

Are you running your crew in a clean Virtual env?

**Comment by hiddenkirby** [comment]
I am experiencing this on the streamlit.io deployment of my CrewAI (v0.36.1) app since they install `http://deb.debian.org/debian bullseye/main amd64 sqlite3 amd64 3.34.1-3`.  I am running Python 3.12... and it doesn't seem to matter what version of Python I choose in the cloud configuration.

3.12.4 for local development.  Everything works in development. 
> [tool.poetry.dependencies]
> python = ">=3.10,<=3.13"
> crewai = "^0.36.1"
> streamlit = "^1.35.0"
> python-dotenv = "^1.0.1"
> docx2txt = "^0.8"
> exa-py = "^1.0.12"
> crewai-tools = "^0.4.0"
> langchain-openai = "^0.1.7"
> python-docx = "^1.1.2"
> markdown2 = "^2.4.13"
> pypandoc = "^1.13"
> markdown2docx = "^0.1.0"
> pydantic = "^2.8.2"

* I wasn't able to install pysqlite3-binary (0.5.3.post1). It would just fail.
* I started to try and pin to chromadb 0.3.29 and downgrade libraries but that got messy fast. 
* I was able to spin up chroma in a docker container and use it, but I don't know how to update the crewai_tools to use a remote chromadb.

**Comment by MrSimonC** [comment]
**Regression Issue: CrewAI 0.74.0 Fails to Recognize Supported SQLite Version**

**Description:**

I've encountered this very same regression issue where CrewAI 0.70.1 works successfully when creating a new crew, but CrewAI 0.74.0 fails to recognize the supported version of SQLite.

**Reproduction Steps:**

1. Create a new project with a `requirements.txt` file containing:
```
crewai==0.70.1
crewai-tools
```
2. Run `pip install -r requirements.txt` and then `crewai create crew exampleproject1`. This works successfully.
3. Update the `requirements.txt` file to:
```
crewai==0.74.0
crewai-tools
```
4. Run `pip install -r requirements.txt` and then `crewai create crew exampleproject2`. This fails with the error message:
```
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
```
**Environment:**

* Running on a brand new project on a new repository on a GitHub codespace
* Python 3.12.1

**Additional Information:**

* Running `sqlite3 --version` returns `3.45.3 2024-04-15 13:34:05 8653b758870e6ef0c98d46b3ace27849054af85da891eb121e9aaa537f1e8355 (64-bit)`, which meets the required version.

I'm picking up my interest in this project after a few months away and so I will stick with v0.70.1 for now since this is working...

**Comment by MrSimonC** [comment]
A bit of an update from me… After looking into this for quite a while, I can now confirm that CrewAI code is actually fine, it's all to do with the users set up.

First thing I confirm everything is working correctly ([I've made an example repo](https://github.com/MrSimonC/CrewAI-Working-Example-AzureOpenAI)) on version `crewai==0.74.2` and `crewai-tools==0.13.2`. On my set up, I was trying to use GitHub code spaces. It turns out the universal image uses Ubuntu LTS 20 with a very old version of sqlite3. When Python is installed, it looks for the locally installed version of sqlite3 and uses that. Therefore, if one has an old version of sqlite3, updating Python makes no difference. Abandoning the GitHub Codespaces universal image for `python:1-3.12-bullseye` this _also_ comes with an old version of sqlite3 - making it non viable to run with CrewAI.

In the end, to get it working, I pulled the latest (pinned) ubuntu image `mcr.microsoft.com/vscode/devcontainers/base:ubuntu-24.04` then installed python3 after. This comes with a much higher version of sqlite3 and resolves the issue, then CrewAI quickstart works well.

**Comment by toadlyBroodle** [comment]
got same sqlite error running `crewai create crew my_project` on Ubuntu, in fresh venv, with `pip install crewai` but `pip install crewai==0.74.0` works fine

**Comment by tsukhu** [comment]
Same issue faced with Azure App Service deployments with the latest version of crewai
Dear @joaomdmoura - we are also facing this issue and are unable to apply the workaround as well . As a result stuck with the earlier version of crewai which does not have have the chromadb dependency.

**Comment by arturogf** [comment]
> A bit of an update from me… After looking into this for quite a while, I can now confirm that CrewAI code is actually fine, it's all to do with the users set up.
> 
> First thing I confirm everything is working correctly on version `crewai==0.74.2` and `crewai-tools==0.13.2`. On my set up, I was trying to use GitHub code spaces. It turns out the universal image uses Ubuntu LTS 20 with a very old version of sqlite3. When Python is installed, it looks for the locally installed version of sqlite3 and uses that. Therefore, if one has an old version of sqlite3, updating Python makes no difference. Abandoning the GitHub Codespaces universal image for `python:1-3.12-bullseye` this _also_ comes with an old version of sqlite3 - making it non viable to run with CrewAI.
> 
> In the end, to get it working, I pulled the latest (pinned) ubuntu image `mcr.microsoft.com/vscode/devcontainers/base:ubuntu-24.04` then installed python3 after. This comes with a much higher version of sqlite3 and resolves the issue, then CrewAI quickstart works well.

can you provide your devcontainer.json file? I am having issues with having python and pip installed

**Comment by 4F2E4A2E** [comment]
Thank you for crewai. I have been trying all possible ways of installing crewai and none of them are working, specially the official ways of installation.

Environment
```Dockerfile
FROM python:3.12-bullseye

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install crewai crewai-tools

CMD ["sleep", "infinity"]
```

Verify
```bash
$ pip freeze | grep crewai
crewai==0.86.0
crewai-tools==0.17.0
```

Try to run
```bash
$ crewai --help
Traceback (most recent call last):
  File "/usr/local/bin/crewai", line 5, in <module>
    from crewai.cli.cli import crewai
  File "/usr/local/lib/python3.12/site-packages/crewai/__init__.py", line 3, in <module>
    from crewai.agent import Agent
  File "/usr/local/lib/python3.12/site-packages/crewai/agent.py", line 8, in <module>
    from crewai.agents import CacheHandler
  File "/usr/local/lib/python3.12/site-packages/crewai/agents/__init__.py", line 2, in <module>
    from .parser import CrewAgentParser
  File "/usr/local/lib/python3.12/site-packages/crewai/agents/parser.py", line 5, in <module>
    from crewai.utilities import I18N
  File "/usr/local/lib/python3.12/site-packages/crewai/utilities/__init__.py", line 13, in <module>
    from .embedding_configurator import EmbeddingConfigurator
  File "/usr/local/lib/python3.12/site-packages/crewai/utilities/embedding_configurator.py", line 3, in <module>
    from chromadb import EmbeddingFunction, Documents, Embeddings
  File "/usr/local/lib/python3.12/site-packages/chromadb/__init__.py", line 86, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.

```

**Comment by 4F2E4A2E** [comment]
related https://github.com/crewAIInc/crewAI/issues/1841
